### ISSUE TITLE
Exception due to not quite CF grid mapping

### ISSUE THREAD

**Issue by rschmunk** [Unidata/netcdf-java#318]
Working with the latest 5.4.0 SNAPSHOT.

Trying to open (enhanced) a WCDAS GOES-16 dataset which has global metadata claiming to follow the CF-1.6 convention. But NJ throws an exception because a couple `grid_mapping` attributes are not named as expected. And the file does not get opened.

Specifically, the `grid_mapping` var looks like

```
int fixedgrid_projection;
  :grid_mapping_name = "geostationary";
  :latitude_of_projection_origin = 0.0; // double
  :longitude_of_projection_origin = -75.00000000000001; // double
  :semi_major = 6378137.0; // double
  :semi_minor = 6356752.31414; // double
  :perspective_point_height = 3.5785831E7; // double
  :sweep_angle_axis = "x";
```

The problem is that the axes attributes are expected to be named `semi_major_axis` and `semi_minor_axis`. So NJ throws an exception that "Must specify semi_major_axis".

Although it's easy enough to modify NJ to handle this specific case, are there arguments against doing so?

**Comment by lesserwhirls** [comment]
Is this a special product being generated by WCDAS that's not typically produced by NOAA, or is this operational? Rather than trying to handle this in the class that handles CF conventions, I'd rather extend that class to handle this as a one off case. I would also recommend reaching out to WCDAS to let them know that this isn't quite CF, and maybe more importantly, they are not in alignment with the GOES Product Definition and User’s Guide.  Do you have a sample I could work with?

**Comment by rschmunk** [comment]
@lesserwhirls, I'm not sure of the dataset origin. I was examining some problems in my code in plotting projected grid data, and the WCDAS/GOES dataset was one of the few sample projected grid files I happened to have on the laptop I've been using for development since the office shifted to teleworking. Global metadata suggest it's legit product, but the file is a couple years old so perhaps is a preliminary version.

I just did a quick Google and the third hit pointed to an AWS-hosted OpenDAP server with GOES-16 data in which  the grid_mapping has been adjusted to the redundant-ish

 ```
  :semi_major = 6378137.0; // double
  :semi_major_axis = 6378137.0; // double
  :semi_minor = 6356752.31414; // double
  :semi_minor_axis = 6356752.31414; // double
```

**Comment by rschmunk** [comment]
I've discovered a few more example GOES-16 projected grid datasets on this laptop hard drive. The older ones dated 2017 have just the non-CF axes attribute names. But one dated 2018 has those plus the valid CF attributes, as in the OpenDAP example I mentioned above. So perhaps there was a change in the production of the datasets to fix the attribute names and make them CF-compliant. In which case, my issue would pretty much be moot.

But one thing that could still be considered a problem (at least for the clueless user) is that an application trying to acquire one of the "deficient" datasets in enhanced mode would fail and the file is not opened, perhaps with little or no reportage of why. Would it make more sense to modify the procedure so that the dataset is acquired but the coordinate system is built without the broken coordinate transform?

**Comment by lesserwhirls** [comment]
I did a little digging on our side, and I believe these files are coming from NOAAPORT, although not directly. When GOES-16/17 netCDF based products are sent across NOAAPORT, they are tiled, and the recipient needs to reassemble them. Given that the recipient needs to reassemble them, all kinds of things can happen. The individual tiles do not use the correct attributes, and if they are reassembled "as-is", the resulting file will not have the correct attributes either. At Unidata, our tile assembling script removes the incorrect attributes and replaces them with the correct ones. It looks like another variant is to keep the incorrect attributes, but also add the correct ones. As a side note, we also generate products directly from the GOES Rebroadcast using SSECs [Community Satellite Processing Package for Geostationary Data](https://cimss.ssec.wisc.edu/csppgeo/), which handles the metadata correctly. It looks like whatever product generator in use by NOAA does not use the correct attributes prior to the files getting tiled and transmitted across the NOAAPORT distribution system.

So, that's what I know there. If people are looking for `semi_major` because that's what the source files from NOAAPORT have, then it makes sense to keep them while adding the correct version to support the widest general use case.

All of that said, I think the best path forward for netCDF-Java is to modify the `CF1Convention` `augmentMetadata` methods (old and new code) to check if we are dealing with one of these files, and modify the projection variable such that we rename the incorrect attribute names to the correct attribute names if does not already have the correct version. If both versions are there, we won't need to do anything. I can knock this out today if that sounds good to you.

**Comment by lesserwhirls** [comment]
Also, if you could point me to an example, that'd be much appreciated. I've searched and searched, but I can only find correct files...I made a request for a level 2 file from 2017 from NOAA's CLASS, but have not heard back from the service yet. I wasn't able to find the opendap server that had files with both, but it's probably because my google filter bubble is getting in the way.

**Comment by lesserwhirls** [comment]
I did a little more digging and found an example on a [TDS that has both](https://thredds.aos.wisc.edu/thredds/dodsC/satellite/GOES/GOES16/PRREGI/Channel07/20200609/GOES16_PRREGI_20200609_181017_3.90_2km_17.4N_67.5W.nc4.html). That one is restitched by a program we made here at Unidata, and it contains both attributes. What I still cannot find is one that only has the incorrect ones.

**Comment by rschmunk** [comment]
@lesserwhirls, The example file that got me looking at this is [here](https://www.dropbox.com/s/1pb2754rsp3v0jw/OR_EFD-060.nc?dl=0). That uses the geostationary projected grid. I have a few other examples with the non-compliant attributes that use the either the geostationary or Lambert conformal conic grid. All are dated 2016 or 2017.

**Comment by rschmunk** [comment]
@lesserwhirls, It turns out that the file I linked to has another oddity/problem. If you check the units of the x and y grid axes, they are "microradian". Although it looks like one of the `Geostationary` classes in NJ has some code for doing axis unit conversions, it doesn't seem to be figuring this one out. If I plot the data on a lon-lat map using the coordinate transform provided by NJ, the scaling factor is plainly not right.

**Comment by lesserwhirls** [comment]
Thank you for the followup! I can see the root issue at play, and will get a fix in (hopefully today).

**Comment by lesserwhirls** [comment]
Ok, I have a fix for this in now, and will be sure this gets into the next release (`v5.3.3`) in addition to the 5.4.0 SNAPSHOTs. Thank you for your help identifying the issues here @rschmunk!

**Comment by rschmunk** [comment]
@lesserwhirls, Just a note to say that I am still seeing scaling problems trying to plot geostationary gridded data. Playing with the sample dataset and another similar that use microradian for the x/y units, I'm finding I need to scale the transform by 1e6 or 1e-6 (as appropriate) to get a map that looks right. I'm poking at source to see if I can find if/where there might be a problem, but don't have an answer yet.
