### ISSUE TITLE
Variable.setCachedData vs. Variable.Builder.setSourceData

### ISSUE THREAD

**Issue by haileyajohnson** [Unidata/netcdf-java#585]
Updating the IOSP example docs (#525) exposed a small discrepancy in the public API for caching variable data between v.  5 and 6:

v.5: `Variable.setCachedData(Array cacheData)` is deprecated in favor of `Variable.Builder.setCachedData(Array cacheData)`.

v.6: 'Variable.setCachedData(ucar.array.Array cacheData) still exists, but is `protected` and called by Variable reads.
`Variable.Builder` replaced `setCachedData` with `setSourceData`

Which mean that using `Variable.Builder.setCachedData` breaks without warning on the move to v.6.

Possible solution: bring `Variable.Builder.setCachedData` back into 6 as a wrapper for `setSourceData` and add deprecation warning?

**Comment by lesserwhirls** [comment]
I think bringing it back a wrapper with a warning makes sense. @JohnLCaron - anything I'm missing?

**Comment by JohnLCaron** [comment]
Good catch!

I dont think anyone should be messing with the internal cache; its all kinds of wrong.
So I think that we should deprecate it in 5, with no replacement.

**Comment by JohnLCaron** [comment]
Ok now that Im thinking clearly:

1. We dont want to make Variable.setCachedData public in ver6. We do need to set the cache in the Variable.Builder, its one of the main ways we get data into a variable. Its just when we build a Variable, we need it to be effectively immutable.

2. Change the deprecation in v5 to "Variable.setCachedData(Array cacheData) is deprecated in favor of Variable.Builder.setCachedData(ucar.ma2.Array cacheData). In version 6 it will be changed to Variable.Builder.setSourceData(ucar.array.Array<?> cacheData)".

3. In ver 6, revert to Variable.Builder.setCachedData(ucar.ma2.Array cacheData), so theres no "break without warning". This method itself will be deprecated in ver6 in favor of setSourceData(), since ucar.ma2.Array is going away in ver7.

If everyone agrees, ill submit some PRs.

**Comment by JohnLCaron** [comment]
Can we close this?
