### ISSUE TITLE
Problems with logging bindings in ver6

### ISSUE THREAD

**Issue by JohnLCaron** [Unidata/netcdf-java#671]
Various problems with logger bindings collected here.

**Comment by JohnLCaron** [comment]
Task :uicdm:ToolsUI.main()
ClassForName java.awt.RectangleSLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/snake/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/snake/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-jdk14/1.7.28/7dd18b408288ad35cd4021a6e50f0e6e8c6454de/slf4j-jdk14-1.7.28.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

**Comment by JohnLCaron** [comment]
./gradlew test

> Configure project :httpservices
Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .

> Configure project :opendap
Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .

**Comment by lesserwhirls** [comment]
> Task :uicdm:ToolsUI.main()

I have a fix for this one (just needed to exclude `slf4j-jdk14` which gets pulled in with `gcdm`).

> ./gradlew test
> 
> > Configure project :httpservices
> > Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .
> 
> > Configure project :opendap
> > Found slf4j-api dependency but no providers were found.  Did you mean to add slf4j-simple? See https://www.slf4j.org/codes.html#noProviders .

These are both warnings generated by gretty at configuration time. When you apply the gretty plugin, it checks to see if the project it is being applied to uses `slf4j-api`. If so, it does a check to see if an slf4j binding is in the runtime configuration of the project. It used to be that if one was not found that it would add the `slf4j-nop` binding as a project dependency (silently), and your build would pick up a dependency without any warning. This [PR](https://github.com/gretty-gradle-plugin/gretty/pull/9) changed that behavior such that it is now just a warning instead of adding the `nop` binding, which is nicer behavior. It's a good thing if you are using gretty to test server code, as you would expect the server to have a logger that functions. For our cases, however, we are using gretty to spin up a server from an external artifact to test client code, and the client code does not have a binding as part of the runtime config (testRuntime, yes, but not runtime).

Unfortunately, gradle does allow you to configure individual package log levels, so I can't just turn off warnings for gretty...we're stuck with these for now. I could see about fixing gretty to do the right thing in our case (gretty testing client code), but that will take some time to make it through the process and into a release. Since we are only looking to spin up a server locally for testing client code, and are not looking to generate code coverage metrics on the sever side (since that codebase lives elsewhere), we could move away from gretty and go with a docker based solution (I've used something like this over at https://github.com/lesserwhirls/cdm-rpc/tree/main/cdm-grpc-local#spinning-up-a-local-server). Or maybe there is another way out there as well.

**Comment by JohnLCaron** [comment]
AFAICT, the warnings only happen on those two modules, was wondering about
that?

**Comment by lesserwhirls** [comment]
On the `develop` branch, only three projects use gretty - `httpservices`, `opendap`, and `cdm-lite`.  We don't see the warning with `cdm-lite` because it has an slf4j binding dependency on the runtime configuration:

https://github.com/Unidata/netcdf-java/blob/62fa2b69f588b202ccdb346682d2460fcb7198cc/cdm-lite/build.gradle#L32

**Comment by JohnLCaron** [comment]
Ok by me to close this when #671 is in.
